import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Map from "../components/Map";
import Header from "../components/Header/header";
import Footer from "../components/Footer/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>The Expo Line</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className="bg-frogGreen text-4xl text-offWhite p-8  ">
        <h1 className="text-center font-Heebo text-darkBlue ">
          The SkyTrain's Expo Line Stations
        </h1>

        <Map></Map>

        <div className="flex flex-col justify-center w-full ">
          <h2 className=" mb-2 text-4xl font-Heebo text-darkBlue">Expo Line</h2>
          <p className=" mb-2 text-xl font-DMSans text-offWhite">
            The Expo Line operates two routes:
          </p>
          <ul className="mb-3 list-inside ml-5 list-disc">
            <li className="text-xl font-DMSans text-offWhite">
              Waterfront Station (Downtown Vancouver) to King George Station
              (Surrey)
            </li>
            <li className="text-xl font-DMSans text-offWhite">
              Waterfront Station (Downtown Vancouver) to Production
              Way–University Station (Burnaby)
            </li>
          </ul>
          <p className=" mb-2 text-xl font-DMSans text-offWhite">
            Transfer to the Millennium Line at the following stations:
          </p>
          <ul className="mb-3 list-inside ml-5 list-disc">
            <li className="text-xl font-DMSans text-offWhite">
              Waterfront Station (Downtown Vancouver) to King George Station
              (Surrey)
            </li>
            <li className="text-xl font-DMSans text-offWhite">
              Waterfront Station (Downtown Vancouver) to Production
              Way–University Station (Burnaby)
            </li>
          </ul>
          <p className=" mb-3 text-xl font-DMSans text-offWhite">
            Use Columbia Station to transfer to and from a train going to either
            King George or Production Way–University.
          </p>
          <p className=" mb-3 text-xl font-DMSans text-offWhite">
            Use Waterfront Station to transfer to the Canada Line, SeaBus, or
            West Coast Express.
          </p>
        </div>
      </main>

      <Footer></Footer>
    </>
  );
}
